### ISSUE TITLE
Got the following error -Request denied by Cloud IAM.", "status": "PERMISSION_DENIED"

### ISSUE THREAD

**Issue by d0uble3L** [somethingnew2-0/gcp-cspm-sheets#1]
Exception: Request failed for https://cloudasset.googleapis.com returned code 403. Truncated server response: { "error": { "code": 403, "message": "Request denied by Cloud IAM.", "status": "PERMISSION_DENIED", "details": [ { ... (use muteHttpExceptions option to examine full response)

Any tips to torubelshoot

**Comment by somethingnew2-0** [comment]
As mentioned in the [Installation guide](https://simplecspm.com/#install):

> Add the following GCP IAM roles for your user on your GCP organization
> roles/cloudasset.viewer
> roles/recommender.iamViewer
> roles/recommender.projectUtilViewer
> roles/recommender.cloudAssetInsightsViewer
> roles/recommender.firewallViewer
> roles/serviceusage.apiKeysViewer
> roles/securitycenter.findingsViewer

**Comment by d0uble3L** [comment]
Created custom role with the following still no luck. 

```
Description
Created on: 2022-01-13 Based on: Cloud Asset Viewer, Cloud Asset Insights Viewer, Firewall Recommender Viewer, IAM Recommender Viewer, Project Utilization Recommender Viewer, Security Center Findings Viewer, API Keys Viewer, Service Usage Admin
```

**Comment by d0uble3L** [comment]
nvm, got it to work. 
role was created and applied on project level not org level.  big oof! thanks
