### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by d0uble3L** [somethingnew2-0/gcp-cspm-sheets#2]
Recieve the following Google Sheets Error

`TypeError: Cannot read property 'forEach' of undefinedDetails
`

**Comment by somethingnew2-0** [comment]
Can you collect the line number?

In your spreadsheet go to `Extensions` -> `App Script`
<img width="321" alt="Screen Shot 2022-01-13 at 1 16 59 PM" src="https://user-images.githubusercontent.com/1957198/149386552-8e16dd3d-3b23-40c0-993c-9c46257f34cf.png">

Then click `Run` or `Debug` with the `runAudit` function selected
<img width="809" alt="Screen Shot 2022-01-13 at 1 17 09 PM" src="https://user-images.githubusercontent.com/1957198/149386563-7e27262b-3347-43f7-8dc7-1efa316c84a2.png">

**Comment by d0uble3L** [comment]
`TypeError: Cannot read property 'forEach' of undefined
(anonymous)	@ Code.gs:453
fetchAllAssets	@ Code.gs:305
auditPublicAppEngine	@ Code.gs:452
auditPublicCloudAssetInventory	@ Code.gs:134
runAudit	@ Code.gs:40`

**Comment by somethingnew2-0** [comment]
Ah I see the issue.  Fixed in https://github.com/somethingnew2-0/SimpleCSPM/commit/decc59d8ec33ece53b6935aa048fb4fb26b8b875

Feel free to copy paste https://github.com/somethingnew2-0/SimpleCSPM/blob/main/Code.js into your Code.gs Apps Script editor to fix it

**Comment by d0uble3L** [comment]
thank you very much! looks like its working and no errors.
